### ISSUE TITLE
Cannot npm install with Git URL

### ISSUE THREAD

**Issue by seven1m** [kenwheeler/mcfly#15]
Seems to be because `lib` directory is not present on GitHub, but the package.json refers to it.

I'd like to try out the master branch, but I cannot :sob:

**Comment by balanceiskey** [comment]
Hey, just curious, any update on this?

**Comment by kenwheeler** [comment]
Coming in the next day or so, sorry, been busy at my full time

**Comment by balanceiskey** [comment]
No worries! Keep on rockin'.

**Comment by kenwheeler** [comment]
Fixed
