### ISSUE TITLE
Allow Multiple Independent Instances

### ISSUE THREAD

**Issue by justinanastos** [kenwheeler/mcfly#17]
I am trying to write an video player that has multiple with mcfly. I have everything working, but if I create multiple instances of the player on a single page, they seem to copy each other. I believe this comes from using a single Dispatcher for all new instances of mcfly. Is this desired behavior? Is there a way around it?

**Comment by tomatau** [comment]
They wouldn't need to know about each other using the above suggestion..? - actions can add instance information to a store that is then used to add instances to the page by a parent component.

**Comment by kenwheeler** [comment]
I think he doesn't want a parent component. But you could still share a store, and have instance specific data, where they wouldn't "know about one another"

**Comment by tomatau** [comment]
That's it - alternatively each video component could also supply instance information to the action creator that's used in the loading bar - then the videos can take control of their own uniqueness.
