### ISSUE TITLE
Problems testing with Jest and invariant

### ISSUE THREAD

**Issue by ferrannp** [kenwheeler/mcfly#18]
Hello Ken, I had some tests following this technique http://facebook.github.io/react/blog/2014/09/24/testing-flux-applications.html

However, I am having some troubles using McFly. I tried to write a test using your library example.

    jest.dontMock('../CounterStore');
    jest.dontMock('../../flux/mcFly');

    describe('CounterStore', function() 
    {
       it('expects store to be defined', function() {
         CounterStore = require('../CounterStore');
         expect(CounterStore).toBeDefined();
       });
    });

This test fails.

What I do is add this to the package.json:

    "jest": {
       "rootDir": ".",
        "scriptPreprocessor": "../jest-preprocessor.js",
        "unmockedModulePathPatterns": [
          "./node_modules/react",
          "./node_modules/mcfly"
        ]
     },

Then the test passes ok. However, in my project I also use react-tools. It's giving me a very weird error:

    MyStore.js: __DEV__ ist not defined
    .../node_modules/react-tools/src/vendor/core/invariant.js:26:7
    .../node_modules/mcfly/lib/Store.js:21:5
    .../node_modules/mcfly/lib/McFly.js:32:17

I saw in line 21 of mcfly Store there is:
    
    invariant(!methods.callback, '"callback" is a reserved name and cannot be used as a method name.');
 
But it is using the invariant library from react-tools instead of the one from mcfly! Is this a library problem? Or am I using the packages very wrong? Not sure if this is mcfly related o a Jest problem.

This is not happening with the example of this library (still using 0.0.2) but if you change the package.json to:

     "dependencies": {
       "mcfly": "0.0.8",
       "react": "^0.12.0",
       "underscore": "^1.7.0"
     },

Then:

     - ReferenceError: /Users/xxx/Desktop/mcfly-master/example/js/stores/CounterStore.js: __DEV__ is not defined
        at invariant (/Users/xxx/Desktop/mcfly-master/example/node_modules/react-tools/src/vendor/core/invariant.js:26:7)
        at new Store (/Users/xxx/Desktop/mcfly-master/example/node_modules/mcfly/lib/Store.js:21:5)
        at McFly.createStore (/Users/xxx/Desktop/mcfly-master/example/node_modules/mcfly/lib/McFly.js:32:17)
        at /Users/xxx/Desktop/mcfly-master/example/js/stores/CounterStore.js:9:26

EDIT:
If in Jest configuration I do:

    "globals": {"__DEV__": true}

Then all tests are ok but I feel like cheating? But actually if I try:

    var mockStore.mcFly.createStore({
      mixin: function(){
        return null
      }
        ...
    })

Then it tells me:

    Invariant violation: "mixin" is a reserver name and cannot be used as a method name
(which is from McFly invariant so... maybe I am not doing anything wrong at the end).

**Comment by davidreher** [comment]
I am having the same issue when testing some react component ... What do you mean by namespacing it? Should I namespace the component? How would you do that and how would you reference the component? 

Why doesn't this occur when running the code in the browser?

**Comment by kenwheeler** [comment]
@davidreher I think my invariant and Facebooks invariant are colliding. Therefore I would name invariant like iv or something.

**Comment by ferrannp** [comment]
Hello again,

Using mcfly 0.0.10 and Jest 0.4.0, I am still seeing this error:

    __DEV__ is not defined
      at invariant (.../node_modules/react-tools/src/vendor/core/invariant.js:26:7)
      at new Store (.../node_modules/mcfly/lib/Store.js:23:5)         
      at McFly.createStore (.../node_modules/mcfly/lib/McFly.js:34:17)

I wonder if the reason is coming from doing this:

    "unmockedModulePathPatterns": [
      "<rootDir>/node_modules/react",
      "<rootDir>/node_modules/mcfly"
    ]

But without mcfly there I had other problems...

**Comment by tomatau** [comment]
often I need to use this in my tests around McFly stores
```
jest.mock('mcfly/node_modules/flux');
```
As well as not mocking my mcFly instance.

also you can add globals to the package.json
```
  "jest": {
    "globals": {
      "__DEV__": true,
    },
```

**Comment by ferrannp** [comment]
Hi! Yea maybe I would have to try removing ```  "<rootDir>/node_modules/mcfly"``` and check the tests...

Adding the global __DEV__ variable does the trick but it seems very hacky to me.

**Comment by tomatau** [comment]
I think you'll still need to keep the unmockedModulePathPatterns for mcfly so that stores and actions can be created and tested. I just make sure that the flux dependency of McFly still does get mocked (which contains invariant)

In my build, we use a __DEV__ flag in our source anyway as it's a common practice so the global flags in the test runner make logical sense.

I think you could also add this to your test file to achieve the same goal (not sure how jest plays with this):
```
GLOBAL.__DEV__ = true
```

**Comment by JeffreyLeeSpokeo** [comment]
I tried to add the globals to my package.json, but it didn't work I still see the error __DEV__ is not defined

**Comment by psalv** [comment]
How would one go about modifying the globals within the tests? So for instance if I wanted __DEV__ to be true for one test, and then false for another.

**Comment by alexgvozden** [comment]
> How would one go about modifying the globals within the tests? So for instance if I wanted **DEV** to be true for one test, and then false for another.

just update value of window.__DEV__ to change it
