### ISSUE TITLE
onChange renamed to something more descriptive?

### ISSUE THREAD

**Issue by pselden** [kenwheeler/mcfly#19]
What are your thoughts about renaming onChange to something more descriptive like "onStoreChanged"? Something I've noticed when taking a high level view of my components is that it's not clear exactly what "onChange" is for. Renaming it to "onStoreChanged" might help make that more clear.

Clearly that would be a breaking change, so if you wanted to avoid that (but we're pre 1.0 -- and pre 0.1 :), so why not!) you could add it as an alias.

      componentDidMount: function() {
        self.addChangeListener(this.onChange || this.onStoreChanged);
      },
      componentWillUnmount: function() {
        self.removeChangeListener(this.onChange || this.onStoreChanged);
      }

**Comment by bigblind** [comment]
One thing to think about would be naming consistency. React has component lifecycle hook methods like `componentDidMount`, so a method name like `storeDidChange` would be consistent with react's naming. The `onStoreChange` name would be more consistent with traditional JavaScript event names.

**Comment by kenwheeler** [comment]
@bigblind good point

**Comment by pselden** [comment]
Yeah I think 'storeDidChange' sounds right.

**Comment by kenwheeler** [comment]
Merged
