### ISSUE TITLE
Scoped use of 'use strict' causing issues with eval-ed source maps from webpack in Chrome

### ISSUE THREAD

**Issue by balanceiskey** [kenwheeler/mcfly#22]
On occasion I've been getting a random error in Chrome:

![share](https://cloud.githubusercontent.com/assets/470240/5598425/c1ce8852-927b-11e4-8d08-72bd6af83498.png)

I think the reason for this is the inline 'use strict' in McFly's constructor: 

![share](https://cloud.githubusercontent.com/assets/470240/5598434/e902d5cc-927b-11e4-85dd-52d2b0ffa5c3.png)

My suspicion for this actually stems from an issue with Chrome and a similar issue was occurring with the Facebook's Dispatcher as well:

https://github.com/facebook/flux/issues/45

The solution there was to simply move the 'use strict' to the top of the file.

**Comment by balanceiskey** [comment]
That solution may end up being a bit naive as all the source files apply 'use strict' in this way.

**Comment by kenwheeler** [comment]
Merged
