### ISSUE TITLE
Still using singletons for stores?

### ISSUE THREAD

**Issue by totty90** [kenwheeler/mcfly#3]

**Comment by lapanoid** [comment]
@totty90 I totally agree with your doubts about singletons and testing. If I test something I want to be sure that I have this thing I some particular state. Of coarse I can tear up singletons after each test, but this is an unnecessary burden and price of singletons. If I had a factory to create a store each time, I would not have to worry about tearing up after each test at all. I just get 100% fresh and clean object and I am 100% sure that other tests did not break it.
