### ISSUE TITLE
`Uncaught TypeError: listener must be a function` is hard to trace

### ISSUE THREAD

**Issue by eastridge** [kenwheeler/mcfly#31]
I removed an `onChange` from an example component. I edited a bunch of things, so I wasn't apparent that `onChange` was required and then the `Uncaught TypeError: listener must be a function` error was being thrown. No where in the stack trace pointed me to the file I had modified, so there was no way of knowing what mcfly was looking for.

**Comment by kenwheeler** [comment]
Sorry about that man. I'll try and get 0.0.9 pushed out tonight.

**Comment by eastridge** [comment]
Damn you're fast!
