### ISSUE TITLE
Swap promises for ES6 generators and ES7 async await

### ISSUE THREAD

**Issue by tomatau** [kenwheeler/mcfly#37]
I feel this would greatly improve the API usage and also improve error handling - making the code much clear to avoid things like the dirty `reThrow` function that lives inside Action.

This would require using the babel compiler (6to5) which also supports JSX if mcfly ever goes the route of involving any JSX.

e.g. Currently:
```
let MyActions = mcfly.createActions({
  actionCreator(foo){
    let scopedVar;
    return asyncCall.method(foo)
      .then(resolved=>{
        scopedVar = resolved.bar;
        return asyncCall.anotherMethod(resolved.derp);
      })
      .then(resolved2=>({
        actionType: Constants.EVENT,
        scopedVar, resolved2
      }))
  }
```

Would become, something like this (maybe?):
```
let MyActions = mcfly.createActions({
  actionCreator(foo){
    let resolved = await asyncCall.method(foo)
    let scopedVar = resolved.bar;
    let resolved2 = await asyncCall.anotherMethod(resolved.derp)
    return {
      actionType: Constants.EVENT,
      scopedVar, resolved2
    }
  }
}
```

Which reads much nicer imo and is forward thinking.

It would also help with https://github.com/kenwheeler/mcfly/issues/36

**Comment by kenwheeler** [comment]
That api would require end users to use babel though, correct?

**Comment by tomatau** [comment]
We would just need to use babel in the build process I think? I'm not sure how well it would play with people using McFly in their browserify/webpack/POJ workflow.

**Comment by kenwheeler** [comment]
What do you think about somehow exposing an async prop on an action creator that will allow users to explicitly dispatch?

**Comment by tomatau** [comment]
Pseudo code an example?

**Comment by kenwheeler** [comment]
```
MyActions.getPost.async(function(dispatch){

       dispatch({
            actionType: 'GET_POST_BEGIN',
            loading: true
        });

        $.ajax('/foo/bar/')
        .done(function(data){
             dispatch({
                 actionType: 'GET_POST_SUCCESS',
                 data: data,
                 loading: false
             });
        })
        .fail(function(error){
            dispatch({
                 actionType: 'GET_POST_ERROR',
                 error: error,
                 loading: false
             });
        });

});
```

**Comment by kenwheeler** [comment]
With the above example, MyActions.getPost(param) would still work, async being a special property that doesn't call dispatch implicitly.

**Comment by tomatau** [comment]
Have been using async await in actions anyway and it works nicely

**Comment by kenwheeler** [comment]
Can I see how you're doing that?

**Comment by tomatau** [comment]
Just compiling with babel, runtime and experimental set, here's an example I've just poached and simplified from our src:

```javascript
let ItemActions = flux.createActions({
  async createItem(item){
    try {
      let { id, parentId } = item
        , newItem = await contentItemGateway.createItem(item)
        , page = await fetchPage(id, parentId, ItemsStore.getPage())
        , selectedItem = await selectItem(newItem);
      return {
        actionType            : ItemConstants.CREATE_ITEM,
        item           : newItem,
        items          : page.items,
        page                  : page.page,
        selectedItem          : selectedItem.item,
        }
    } catch(e) {
      return {
        actionType: AppConstants.NOOP
      }
    }
  },
```

**Comment by kenwheeler** [comment]
Holy shit, that's phenomenal

**Comment by tomatau** [comment]
Tempted by enabling babel playground too.. would allow working with memo functions, and static properties for React 0.13 class propTypes and defaults. Lots of goodies!
