### ISSUE TITLE
Store callback firing with undefined actionType

### ISSUE THREAD

**Issue by joshbedo** [kenwheeler/mcfly#41]
Hey everyone! I'm currently implementing a new feature at my company and experiencing a weird issue within my store where the callback fires first with an empty/undefined payload and then it fires again with the correct actionType and payload. Is there anything I should be looking for that could potentially be causing this? I looked over the examples and everything looks pretty straightforward and simple so far. Here is a short video of the behavior. Thanks!

[video](http://screencast.com/t/zuqYDfp2)

**Comment by tomatau** [comment]
Never experienced anything like a double callback firing.

Can you share the code for the action creator that dispatches and if there are more than one. Was hard to see from the video.

**Comment by joshbedo** [comment]
@tomatau yeah i thought it was really odd too and couldn't pinpoint where it was spawning from.

Here is my action
```
import Flux from 'mcflux';
import Dispatcher from 'dispatcher';
import JsonApiParser from 'libs/jsonapi-parser';


export default Flux.createActions({

  fetch (status, orderBy, orderMode, page) {
    Dispatcher.dispatch({ actionType: 'FETCHING_EXPORTS' })
    $.ajax({
      url: '/api/v1/file_exports',
      method: 'get',
      dataType: 'json',
      contentType: 'application/json'
    }).then((response) => {
      var collection = new JsonApiParser(response, 'file_exports').forCollection()
      Dispatcher.dispatch({
        actionType: 'RECEIVED_EXPORTS',
        collection: collection
      });
    }).fail(function(response) {
      console.error('request failed')
    })
  }

})
```

**Comment by kenwheeler** [comment]
McFly automatically dispatches the return value of actions, so your explicit dispatch is actually firing a second one. 

If you want to use this kind of syntax, I recommend using Biff, a McFly fork I'm developing with explicit dispatch syntax.

Otherwise, use McFly promise syntax.

**Comment by tomatau** [comment]
I think that action creators shouldn't be firing a dispatch if the return value is falsey - that's at least what I remember from the promise logic, but I may be wrong - here the return would be undefined and so falsey? Maybe try explicitly returning false - or like Ken says - just change the final dispatch call to a return and return the ajax call too:

```
    return $.ajax({
      url: '/api/v1/file_exports',
...
      var collection = new JsonApiParser(response, 'file_exports').forCollection()
      return {
        actionType: 'RECEIVED_EXPORTS',
        collection: collection
      };
```

**Comment by joshbedo** [comment]
Awesome so adding the return to my ajax call solved the problem. Thanks a lot @tomatau and @kenwheeler.
