### ISSUE TITLE
What am I doing wrong with waitFor and dispatcherID?

### ISSUE THREAD

**Issue by ferrannp** [kenwheeler/mcfly#42]
Not sure if this is very McFly related but here we go, I have two stores and I do something like:

    case ActionTypes.SOME_ACTION: //User clicks
         mcFly.dispatcher.waitFor([SecondStore.dispatcherID]);
         _elements = {};
         break;

And my other store, for the same action, it does:

    case ActionTypes.SOME_ACTION: //User clicks
         Object.assign(_myElements, FirstStore.getElements());
         break;

In the component that I am using them, I require them like:

    var SecondStore = require('../stores/SecondStore');
    var FirstStore = require('../stores/FirstStore');

The error I am getting is:

```Error: Invariant Violation: Dispatcher.waitFor(...): `undefined` does not map to a registered callback.```

So basically, ```SecondStore.dispatcherID``` is undefined. But, if I require them like:

    var FirstStore = require('../stores/FirstStore');
    var SecondStore = require('../stores/SecondStore');

I get:

```TypeError: undefined is not a function
    at Object.ID_2 ```

Which tells me that FirstStore.getElements() is not defined.

What am I missing? I cannot access to FirstStore from SecondStore and to SecondStore from the FirstStore? Am I creating a circular dependency ? The thing is that if in the first example, instead of using ```mcFly.dispatcher.waitFor([SecondStore.dispatcherID]);``` I use the id directly ```mcFly.dispatcher.waitFor(["ID_2"])```;, then works as expected. Can I retrieve the dispatcherID in some other way? something like ```mcFly.dispatcher.ids["SecondStore"]``` ?

--- 
Edit: Oh... maybe it is related to: https://facebook.github.io/react/blog/2014/07/30/flux-actions-and-the-dispatcher.html#why-we-need-a-dispatcher

> Problems arise, however, if we have circular dependencies. That is, if Store A needs to wait for Store B, and Store B needs to wait for Store A, we could wind up in an endless loop. The dispatcher now available in the Flux repo protects against this by throwing an informative error to alert the developer that this problem has occurred. The developer can then create a third store and resolve the circular dependency.

If that is... I'd be nice to see the warning.

**Comment by fisherwebdev** [comment]
Yeah, I think you have a circular dependency.  The first problem you have is how you'll require the stores.  You can get around the require problem with a dynamic, inline require (in some build systems, at least), but this is pretty hacky.

You can just console log the value of SecondStore in FirstStore, and the value of FirstStore in SecondStore.  If one of them comes back as an empty object, `{}`, then your build system is choking on the circular dependency.

The warning is there for situation where you have actually done the hacky require, and now you have set up a circular dependency _for a particular action type_.  

In either case, the answer is always goes 2 to 3 or 2 to 1.  That is, when you have two stores in circular dependency, you need to either create a new store to resolve it, or create a resolution down in the view layer (3 entities, not 2).  Alternatively you can combine the stores into a single store.  (1 entity, not 2).

**Comment by ferrannp** [comment]
Yea, in this case, there was no warning though so I had to debug it a bit. I feel that the option 2 to 1 would be simpler in this case (merging the data when the user clicks).

Thanks for answering :)
