### ISSUE TITLE
Store emit different change names

### ISSUE THREAD

**Issue by mygoare** [kenwheeler/mcfly#43]
Right now Store only have emitChange() function to emit change to react component, which also has only one onChange listener to listen to the change event.

So I want store can emit different change names, and the components can have multi listeners.

**Comment by tomatau** [comment]
You can do this already -- all stores extend from events.

```
MyStore.emit('different-named-event')
```

And within whatever, you can do:

```
MyStore.on('different-named-event', this.myCallback)
```

You could swap `this.myCallback` for `this.storeDidChange`... You wouldn't need to use the MyStore.mixin if you did it manually like this.

**Comment by mygoare** [comment]
thank you very much!

**Comment by mygoare** [comment]
Thank you very  much.

I realize `this.storeDidChange` as a callback only works for when `Store.emit('change')`, also can write as    `Store.emitChange`

**Comment by tomatau** [comment]
For the storeDidChange to work, you would need to use the Store's mixin also.

**Comment by mygoare** [comment]
yes, I know that. mcfly predefine a mixin. Thank you again.
